### ISSUE TITLE
[Button] Make our selector more specific.

### ISSUE THREAD

**Issue by AMANDUA** [collab-ui/collab-ui#162] opened 2019-04-04 07:29 UTC
Can we make our selector more specific in case of applying style to components.

## Issue Type
Bug

## Component or Pattern Affected
Button

## Expected Behavior

Some styling(such as background-color, border-radius ..) gets overridden by collab-ui styling.
Though we can pass ```Style``` props in ```Button``` to apply inline styling.

But there is a concern that is it possible to make our given selector more specific to take all properties of it first and then apply rest styling of collab-ui??

## Possible Solution
Not sure we can say if a user ```className```  is passed then all its styling should be given a higher priority

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by pauljeter** [comment] 2019-04-08 13:54
Duplicate of #149

**Closed by pauljeter** 2019-04-08 13:54 UTC
Labels: duplicate
